### ISSUE TITLE
DM Communication

### ISSUE THREAD

**Issue by No767** [transprogrammer/rodhaj#8]
This issue represents the task of DM communication. In context, this represents the setup process of when a user DMs the bot, and creates a new ticket. This ticket is represented as a forum post on the moderation channel, and thus is the channel for communication between users and admins.

Now, the process is similar to how ModMail performs, but is slightly different. Thus, the steps are represented in the process below.

1. User DMs modmail about their concerns. They will receive a prompt on whether they want to create a modmail thread or not. This prompt is represented as a `discord.ui.View`
2. Once accepted, the coro will dispatch an event using `commands.Bot.dispatch` and adds the current ticket into the database. Within the database, the user id, channel id, creation date, and other metadata (TBD) will be stored. The dispatch will notify an listener to do all of the tasks as described (the creation of the ticket and database storage)

Of course, we will have to check whether the message is indeed a DM or not. If it came from the guild, we will ignore it.

Contacting the user requires further investigation as how modmail handles this

**Comment by jamievlin** [comment]
As a clarification, "They" in point (1) means "The user"
